import { subscriptise } from './utils.js';

const g = 'glyph';
const r = 'reading';
const m = 'meaning';

const corpus = [
  { [g]: '𒀭', [r]: 'diĝir', [m]: 'god' },
  { [g]: '𒈗', [r]: 'lugal', [m]: 'king, master' },
  { [g]: '𒌉', [r]: 'dumu', [m]: 'son, daughter, child' },
  { [g]: '𒂍', [r]: 'e2', [m]: 'house, temple' },
  { [g]: '𒃲', [r]: 'gal', [m]: 'big, great' },
  { [g]: '𒌉', [r]: 'tur', [m]: 'small, young' },
  { [g]: '𒆗', [r]: 'kala(g)', [m]: 'strong, mighty' },
  { [g]: '𒂵', [r]: 'ga', [m]: 'milk' },
  { [g]: '𒆳', [r]: 'kur', [m]: 'mountain, enemy land' },
  { [g]: '𒎏', [r]: 'nin', [m]: 'queen, lady' },
  { [g]: '𒂊', [r]: 'e', [m]: '"hey!"' },
  { [g]: '𒉈', [r]: 'ne', [m]: '' },
  { [g]: '𒂗', [r]: 'en', [m]: 'lord' },
  { [g]: '𒆤', [r]: 'lil2', [m]: 'wind, air' },
  { [g]: '𒀴', [r]: 'nita2', [m]: 'man, male' }, // 𒍑 nita is less frequent. See http://oracc.iaas.upenn.edu/epsd2/cbd/sux/o0036404.html
  { [g]: '𒊏', [r]: 'ra', [m]: '' },
  { [g]: '𒆷', [r]: 'la', [m]: '' },
  { [g]: '𒁺', [r]: 'ĝen', [m]: 'to go, come' },
  { [g]: '𒆭', [r]: 'ku4', [m]: 'to enter' },
  { [g]: '𒉌', [r]: 'i3', [m]: 'oil, fat, butter' },
  { [g]: '𒀀', [r]: 'a', [m]: 'water' },
  { [g]: '𒆕', [r]: 'du3', [m]: 'to build, make' },
  { [g]: '𒈬', [r]: 'mu', [m]: 'name, year' },
  { [g]: '𒂦', [r]: 'bad3', [m]: 'wall, fortification' },
  { [g]: '𒇷', [r]: 'le', [m]: '' },
  { [g]: '𒌦', [r]: 'un', [m]: '' },
  { [g]: '𒌨', [r]: 'ur', [m]: 'dog, beast' },
  { [g]: '𒌷', [r]: 'iri', [m]: 'city' },
  { [g]: '𒈤', [r]: 'maḫ', [m]: 'magnificent' },
  { [g]: '𒁀', [r]: 'ba', [m]: '' },
  { [g]: '𒉈', [r]: 'bi2', [m]: '' },
  { [g]: '𒅗', [r]: 'du11(g)', [m]: 'to say, speak' },
  { [g]: '𒋧', [r]: 'šum2', [m]: 'to give' },
  { [g]: '𒈬', [r]: 'ĝu10', [m]: 'my' },
  { [g]: '𒍪', [r]: 'zu', [m]: 'your (singular)' },
  { [g]: '𒁉', [r]: 'be2', [m]: 'its' },
  { [g]: '𒈨', [r]: 'me', [m]: 'our' },
  { [g]: '𒋀', [r]: 'šeš', [m]: 'brother' },
  { [g]: '𒆠', [r]: 'ki', [m]: 'place, earth' },
  { [g]: '𒂔', [r]: 'eden', [m]: 'plain, steppe' },
  { [g]: '𒀭', [r]: 'an', [m]: 'sky, heaven' },
  { [g]: '𒅈', [r]: 'ar', [m]: 'praise' },
  { [g]: '𒅕', [r]: 'er', [m]: '' },
  { [g]: '𒅕', [r]: 'ir', [m]: '' },
  { [g]: '𒌫', [r]: 'ur2', [m]: 'root, trunk' },
  { [g]: '𒇽', [r]: 'lu2', [m]: 'person, man' },
  { [g]: '𒍑', [r]: 'nita', [m]: 'man, male' }, // 𒀴 nita₂ is more frequent.
  { [g]: '𒂼', [r]: 'ama', [m]: 'mother' },
  { [g]: '𒄄', [r]: 'gi4', [m]: 'to turn, return' },
  { [g]: '𒌓𒁺', [r]: 'e3', [m]: 'to go out' },
  { [g]: '𒊑', [r]: 're', [m]: 'that' },
  { [g]: '𒀝', [r]: 'ak', [m]: 'to do, perform, act' },
  { [g]: '𒈾', [r]: 'na', [m]: '' },
  { [g]: '𒉌', [r]: 'ni', [m]: '' },
  { [g]: '𒃻', [r]: 'ĝar', [m]: 'to set, place' },
  { [g]: '𒉎', [r]: 'ni2', [m]: '' },
  { [g]: '𒈠', [r]: 'ma', [m]: '' },
  { [g]: '𒄑', [r]: 'ĝiš', [m]: 'wood' },
  { [g]: '𒍣', [r]: 'zi', [m]: 'true' },
  { [g]: '𒋗', [r]: 'šu', [m]: 'hand' },
  { [g]: '𒋫', [r]: 'ta', [m]: '' },
  { [g]: '𒁕', [r]: 'da', [m]: 'arm' },
  { [g]: '𒀉', [r]: 'a2', [m]: '' },
  { [g]: '𒂠', [r]: 'še3', [m]: '' },
  { [g]: '𒃻', [r]: 'niĝ2', [m]: 'thing' },
  { [g]: '𒋛', [r]: 'si', [m]: '' },
  { [g]: '𒉎', [r]: 'im', [m]: '' },
  { [g]: '𒇷', [r]: 'li', [m]: '' },
  { [g]: '𒋻', [r]: 'tar', [m]: '' },
].map((item) => ({
  ...item,
  [r]: subscriptise(item[r]),
}));

export default corpus;
