import { subscriptise } from './utils.js';

const g = 'glyph';
const r = 'reading';
const m = 'meaning';

const corpus = [
  { [g]: '𒀭', [r]: 'diĝir', [m]: 'god' },
  { [g]: '𒈗', [r]: 'lugal', [m]: 'king, master' },
  { [g]: '𒌉', [r]: 'dumu', [m]: 'son, daughter, child' },
  { [g]: '𒂍', [r]: 'e2', [m]: 'house, temple' },
  { [g]: '𒃲', [r]: 'gal', [m]: 'big, great' },
  { [g]: '𒌉', [r]: 'tur', [m]: 'small, young' },
  { [g]: '𒆗', [r]: 'kala(g)', [m]: 'strong, mighty' },
  { [g]: '𒂵', [r]: 'ga', [m]: 'milk' },
  { [g]: '𒆳', [r]: 'kur', [m]: 'mountain, enemy land' },
  { [g]: '𒊩𒌆', [r]: 'nin', [m]: 'queen, lady' }, // 𒎏
  { [g]: '𒂊', [r]: 'e', [m]: 'levee, dyke' },
  { [g]: '𒉈', [r]: 'ne', [m]: '' },
  { [g]: '𒂗', [r]: 'en', [m]: 'lord' },
  { [g]: '𒆤', [r]: 'lil2', [m]: 'wind, air' },
  { [g]: '𒀴', [r]: 'nita2', [m]: 'man, male' }, // 𒍑 nita is less frequent. See http://oracc.iaas.upenn.edu/epsd2/cbd/sux/o0036404.html
  { [g]: '𒊏', [r]: 'ra', [m]: '' },
  { [g]: '𒆷', [r]: 'la', [m]: '' },
  { [g]: '𒁺', [r]: 'ĝen', [m]: 'to go, come' },
  { [g]: '𒆭', [r]: 'ku4', [m]: 'to enter' },
  { [g]: '𒉌', [r]: 'i3', [m]: '' },
  { [g]: '𒀀', [r]: 'a', [m]: 'water' },
  { [g]: '𒆕', [r]: 'du3', [m]: 'to build, make' },
  { [g]: '𒈬', [r]: 'mu', [m]: 'name, year' },
  { [g]: '𒂦', [r]: 'bad3', [m]: 'wall, fortification' },
  { [g]: '𒇷', [r]: 'le', [m]: '' },
  { [g]: '𒌦', [r]: 'un', [m]: '' },
  { [g]: '𒌨', [r]: 'ur', [m]: 'dog, beast' },
  { [g]: '𒌷', [r]: 'iri', [m]: 'city' },
  { [g]: '𒈤', [r]: 'maḫ', [m]: 'magnificent' },
  { [g]: '𒁀', [r]: 'ba', [m]: '' },
  { [g]: '𒉈', [r]: 'bi2', [m]: '' },
  { [g]: '𒅗', [r]: 'du11(g)', [m]: 'to say, speak' },
  { [g]: '𒋧', [r]: 'šum2', [m]: 'to give' },
  { [g]: '𒈬', [r]: 'ĝu10', [m]: 'my' },
  { [g]: '𒍪', [r]: 'zu', [m]: 'your (singular)' },
  { [g]: '𒁉', [r]: 'be2', [m]: 'its' },
  { [g]: '𒈨', [r]: 'me', [m]: 'our' },
  { [g]: '𒋀', [r]: 'šeš', [m]: 'brother' },
  { [g]: '𒆠', [r]: 'ki', [m]: 'place, earth' },
  { [g]: '𒂔', [r]: 'eden', [m]: 'plain, steppe' },
  { [g]: '𒀭', [r]: 'an', [m]: 'sky, heaven' },
  { [g]: '𒅈', [r]: 'ar', [m]: 'praise' },
  { [g]: '𒅕', [r]: 'er', [m]: '' },
  { [g]: '𒅕', [r]: 'ir', [m]: '' },
  { [g]: '𒌫', [r]: 'ur2', [m]: 'root, trunk' },
  { [g]: '𒇽', [r]: 'lu2', [m]: 'person, man' },
  { [g]: '𒍑', [r]: 'nita', [m]: 'man, male' }, // 𒀴 nita₂ is more frequent.
  { [g]: '𒂼', [r]: 'ama', [m]: 'mother' },
  { [g]: '𒄄', [r]: 'gi4', [m]: 'to turn, return' },
  { [g]: '𒌓𒁺', [r]: 'e3', [m]: 'to go out' },
  { [g]: '𒊑', [r]: 're', [m]: 'that' },
  { [g]: '𒀝', [r]: 'ak', [m]: 'to do, perform, act' },
  { [g]: '𒈾', [r]: 'na', [m]: '' },
  { [g]: '𒉌', [r]: 'ni', [m]: '' },
  { [g]: '𒃻', [r]: 'ĝar', [m]: 'to set, place' },
  { [g]: '𒉎', [r]: 'ni2', [m]: '' },
  { [g]: '𒈠', [r]: 'ma', [m]: '' },
  { [g]: '𒄑', [r]: 'ĝiš', [m]: 'wood' },
  { [g]: '𒍣', [r]: 'zi', [m]: 'true' },
  { [g]: '𒋗', [r]: 'šu', [m]: 'hand' },
  { [g]: '𒋫', [r]: 'ta', [m]: '' },
  { [g]: '𒁕', [r]: 'da', [m]: 'arm' },
  { [g]: '𒀉', [r]: 'a2', [m]: '' },
  { [g]: '𒂠', [r]: 'še3', [m]: '' },
  { [g]: '𒃻', [r]: 'niĝ2', [m]: 'thing' },
  { [g]: '𒋛', [r]: 'si', [m]: '' },
  // { [g]: '𒉎', [r]: 'im', [m]: '' }, // Not in SantakkuM.
  { [g]: '𒇷', [r]: 'li', [m]: '' },
  { [g]: '𒋻', [r]: 'tar', [m]: '' },
  { [g]: '𒀯', [r]: 'mul', [m]: 'star, planet, constellation' },
  { [g]: '𒅴', [r]: 'eme', [m]: 'tongue, language, speech' },
  { [g]: '𒀳', [r]: 'apin', [m]: 'plow' },
  { [g]: '𒂠', [r]: 'eš', [m]: '' },
  { [g]: '𒂠', [r]: 'gir15', [m]: 'native, local, noble' },
  { [g]: '𒃻', [r]: 'niĝ2', [m]: 'thing' },
  { [g]: '𒋤', [r]: 'sud3', [m]: 'to be far away' },
  { [g]: '𒍣', [r]: 'zig3', [m]: 'to rise, stand' },
  { [g]: '𒅔', [r]: 'in', [m]: '' },
  { [g]: '𒊩', [r]: 'munus', [m]: 'woman, female' },
  { [g]: '𒀊', [r]: 'ab', [m]: 'sea, hole, opening, window' },
  { [g]: '𒀲', [r]: 'anše', [m]: 'donkey, equid, pack animal' },
  { [g]: '𒁾', [r]: 'dub', [m]: 'tablet, document' },
  { [g]: '𒀊', [r]: 'eš3', [m]: 'shrine, sanctuary' },
  { [g]: '𒄤', [r]: 'gaz', [m]: 'to kill, break' },
  { [g]: '𒉋', [r]: 'gibil', [m]: 'to be new' },
  { [g]: '𒅅', [r]: 'ĝal2', [m]: 'to exist' },
  { [g]: '𒄯', [r]: 'ḫar', [m]: 'ring' },
  { [g]: '𒄭', [r]: 'ḫi', [m]: 'to mix up, process' },
  { [g]: '𒄯', [r]: 'ḫur', [m]: 'to scratch, draw' },
  {
    [g]: '𒆬',
    [r]: 'kug',
    // v., to be pure, holy, sacred; to purify, sanctify. adj., bright, white; pure, sacred, holy
    [m]: 'metal, silver, precious metal',
  },
  { [g]: '𒈜', [r]: 'paḫ', [m]: 'leg' },
  { [g]: '𒊕', [r]: 'saĝ', [m]: 'head' },
  { [g]: '𒊬', [r]: 'sar', [m]: 'to write' },
  { [g]: '𒊹', [r]: 'šar2', [m]: 'totality, world, 3,600' },
  { [g]: '𒊿', [r]: 'šen', [m]: 'to be pure, clear' },
  { [g]: '𒂉', [r]: 'tuš', [m]: 'home' },
  { [g]: '𒍠', [r]: 'zag', [m]: 'side, outskirts, frontier, end, limit' },
  { [g]: '𒍢', [r]: 'ze2', [m]: 'you (singular)' },
  { [g]: '𒌓', [r]: 'babbar', [m]: 'to be white' },
  { [g]: '𒁉', [r]: 'be2', [m]: '' },
  { [g]: '𒁉', [r]: 'bi', [m]: '' },
  { [g]: '𒅎', [r]: 'im', [m]: 'clay' },
  { [g]: '𒈧', [r]: 'maš2', [m]: 'goat, sacrificial animal' },
  { [g]: '𒉆', [r]: 'nam', [m]: 'being, fate, destiny' },
  { [g]: '𒎐', [r]: 'nin9', [m]: 'sister' },
  { [g]: '𒊑', [r]: 'ri', [m]: 'to lie upon, press upon' },
  { [g]: '𒀸', [r]: 'aš', [m]: 'to be single, unique, alone' },
  { [g]: '𒁓', [r]: 'bur', [m]: 'offering of food, sacrifice' },
  { [g]: '𒁮', [r]: 'dam', [m]: 'spouse, husband, wife' },
  { [g]: '𒃼', [r]: 'gar3', [m]: 'cake, knob' },
  { [g]: '𒄀', [r]: 'ge', [m]: '' },
  { [g]: '𒄀', [r]: 'gin7', [m]: '' },
  { [g]: '𒍽', [r]: 'ḫuš', [m]: 'to be angry' },
  { [g]: '𒅖', [r]: 'iš', [m]: 'mountain, sand dune' },
  { [g]: '𒈲', [r]: 'muš', [m]: 'snake, reptile' },
  { [g]: '𒉡', [r]: 'nu', [m]: 'image, picture, statue' },
  { [g]: '𒋾', [r]: 'ti', [m]: 'life' },
  { [g]: '𒅥', [r]: 'gu7', [m]: 'to eat' },
  { [g]: '𒉈', [r]: 'izi', [m]: 'fire, brazier' },
  { [g]: '𒄩', [r]: 'ku6', [m]: 'fish' },
  { [g]: '𒅘', [r]: 'naĝ', [m]: 'to drink, irrigate' },
  { [g]: '𒍪', [r]: 'su', [m]: 'to sink, submerge' },
  { [g]: '𒌇', [r]: 'tuku', [m]: 'creditor' },
  { [g]: '𒅇', [r]: 'u3', [m]: 'and, also, furthermore' },
  { [g]: '𒌒', [r]: 'ub', [m]: '' },
  { [g]: '𒄉', [r]: 'ul4', [m]: 'to be quick' },
  { [g]: '𒅗', [r]: 'zuḫ', [m]: 'to steal, rob' },
  { [g]: '𒍎', [r]: 'banšur', [m]: 'table, altar, offering table' },
  { [g]: '𒎏', [r]: 'ereš', [m]: 'lady, queen' },
  { [g]: '𒐈', [r]: 'eš5', [m]: 'three' },
  { [g]: '𒄀', [r]: 'gi', [m]: '' },
  { [g]: '𒄩', [r]: 'ḫa', [m]: '' },
  { [g]: '𒌗', [r]: 'itud', [m]: 'month, moon' },
  { [g]: '𒅗', [r]: 'ka', [m]: '' },
  { [g]: '𒄰', [r]: 'kam', [m]: 'to tune' },
  { [g]: '𒆤', [r]: 'ke4', [m]: '' },
  { [g]: '𒆧', [r]: 'kiš', [m]: 'totality, world' },
  { [g]: '𒎎', [r]: 'na4', [m]: 'stone, pebble, rock' },
  { [g]: '𒉣', [r]: 'nun', [m]: 'prince, noble, master' },
  { [g]: '𒊓', [r]: 'sa', [m]: '' },
  { [g]: '𒋡', [r]: 'sila3', [m]: 'fragment' },
  { [g]: '𒂄', [r]: 'šul', [m]: 'youth, young man, warrior' },
  { [g]: '𒀖', [r]: 'ab2', [m]: 'cow' },
  { [g]: '𒂉', [r]: 'dab5', [m]: 'to seize, take' },
  { [g]: '𒇌', [r]: 'dilim3', [m]: 'oven' },
  { [g]: '𒀀', [r]: 'duru5', [m]: 'to be soft, supple' },
  { [g]: '𒃮', [r]: 'gaba', [m]: 'chest, breast' },
  { [g]: '𒈪', [r]: 'ĝi6', [m]: 'night' },
  { [g]: '𒄾', [r]: 'ḫul2', [m]: 'to rejoice, be happy' },
  { [g]: '𒅗', [r]: 'inim', [m]: 'word, oath' },
  { [g]: '𒌦', [r]: 'kalam', [m]: 'country, land (usually Sumer)' },
  { [g]: '𒆥', [r]: 'kiĝ2', [m]: 'message, order, task' },
  { [g]: '𒆦', [r]: 'kisal', [m]: 'courtyard' },
  { [g]: '𒀞', [r]: 'me3', [m]: 'battle' },
  { [g]: '𒈪', [r]: 'mi', [m]: '' },
  { [g]: '𒉏', [r]: 'nim', [m]: 'fly, insect' },
  { [g]: '𒉚', [r]: 'sa10', [m]: 'to measure out' },
  { [g]: '𒋝', [r]: 'sig', [m]: 'to be weak, slow, thin' },
  { [g]: '𒊮', [r]: 'šag4', [m]: 'heart, inside, interior, middle' },
  { [g]: '𒋻', [r]: 'sila', [m]: 'street, path, road' },
  { [g]: '𒅆', [r]: 'ši', [m]: '' },
  { [g]: '𒋰', [r]: 'tab', [m]: 'to grasp, hold' },
  { [g]: '𒌁', [r]: 'tir', [m]: 'forest, grove, wood' },
  { [g]: '𒌓', [r]: 'u4', [m]: 'day, time, sun' },
  { [g]: '𒊻', [r]: 'uz', [m]: 'duck' },
].map((item) => ({
  ...item,
  [r]: subscriptise(item[r]),
}));

export default corpus;
